// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtzzDF_tcT1l3shDNJ8CzjjJ2pNRXTcA8',
    appId: '1:34189592117:android:4d2ad5810b4aa0ada9d37c',
    messagingSenderId: '34189592117',
    projectId: 'grupaso-pedidos',
    storageBucket: 'grupaso-pedidos.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA0gCnq5ye8_s1SvG7EMaJ2TEg9Scxsmh0",
    authDomain: "grupaso-pedidos.firebaseapp.com",
    projectId: "grupaso-pedidos",
    storageBucket: "grupaso-pedidos.appspot.com",
    messagingSenderId: "34189592117",
    appId: "1:34189592117:web:d74bb0eacd0b5758a9d37c",
  );
}
